FROM python:3.13.0a1

ADD ./sdk/rest/out/python /code/sdk
ADD ./tests /code/tests

WORKDIR /code
RUN pip install sdk/
RUN pip install pytest
WORKDIR /code/tests/api-tests
RUN echo 'pip freeze'
CMD sleep 2 && pytest -vv