version: "3.2"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    environment: 
      - SPEC_DIR=${SPEC_DIR:-openAPI/}
      - SPEC_FILE=${SPEC_FILE:-api.yaml}
      - PORT=${PORT:-8080}
      - HOST=${HOST}
  tester:
    build: 
      context: .
      dockerfile: Dockerfile.tester
    environment: 
      - PORT=${PORT:-8080}
      - HOST=${HOST:-web}
    # volumes:
    #   - .:/code
