FROM python:3.6

ADD ./sdk/rest/out/python /code/sdk
ADD ./tests /code/tests

WORKDIR /code
RUN pip install sdk/
WORKDIR /code/tests/api-tests
RUN echo 'pip freeze'
CMD sleep 5 && python test_basic_api.py