version: "2"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/code

  tester:
    build: 
      context: .
      dockerfile: Dockerfile.tester
    # volumes:
    #   - .:/code
